cheatApp/urls.py
from django.urls import path
from . import views

app_name = 'cheatApp'


urlpatterns = [
    path('',  views.home_view, name='home_view'),
    path('mySheets/', views.mySheets, name='mySheets')
]

cheatsheet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    
    path('', include('cheatApp.urls', namespace='cheat'), name='react-collpasible'), #namespace ???
    path('admin/', admin.site.urls),
    path('coll/',TemplateView.as_view(template_name='index.html'))
]

cheatApp/models.py
from django.db import models

# Create your models here.

cheatApp/views.py
from django.shortcuts import render

# Create your views here.


def home_view(request):


    return render(request, 'base.html' )



def mySheets(request):

    return render(request, 'MySheets\sheets.html')

cheatApp/templates/MySheets/sheets.html
{% extends "base.html" %}
{% load static %}

{% block site %}Sheets Section{% endblock %}

{% block content %}
<div class="main">
    <div class="myCheatSheets">
        <h1>My CheatSheets Section</h1>
    </div>
    <div class="addCheat">
        <!-- React Animation -->
        <div id="react-container">
            <div class='accordion'>
                <div class="titleConsult">
                    <div class=title>
                        <h1>Python</h1>
                        <span>+</span>
                    </div>
                    
                   
                    <ul class=ulConsult>
                        <li>Functions
                            <ul>
                                <li>positional functions</li>
                                <li>Que pedo</li>
                            </ul>
                        </li>
                    
                        <li>Lambda</li>
                    </ul>
                    
                </div>

                <div class="titleConsult">
                    <div class=title>
                        <h1>Pandas</h1>
                        <span>+</span>
                    </div>
                    
                   
                    <ul class=ulConsult>
                        <li>Functions
                            <ul>
                                <li>positional functions</li>
                                <li>Que pedo</li>
                            </ul>
                        </li>
                    
                        <li>Lambda</li>
                    </ul>
                    
                </div>
                
            </div>
            

           
        </div>
         <!-- add button -->
        <button class='btnAdd'>
            <i class="fas fa-plus"></i>
        </button>
        
       
    </div>

    
</div>  
{% endblock %} 

cheatApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   
    <title>{% block site %}Cheat Sheet App{% endblock %}</title>
    <!-- Css -->
    <link href="{% static "css\style.css" %}" rel= "stylesheet">
    <!-- FONTS -->
    <!-- Oxigen font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">
    <!-- Title font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav >
        <div class='logo'>
            <h4>My Logo</h4>
        </div>
        <ul class="SignIn">
            
            <li>
                <a href='#'>Sign in</a>
            </li>
        </ul>
        <!-- <div class="burger" >
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div> -->
    </nav>
    <div id="content">
        {% block content %}
        <div class="mainContent">
            <div class="welcomeApp">
                <h1>CheatSheet App</h1>
                <p>Cheatsheets for programmers</p>
            </div>
            <div class="btnSection">
                <a href="{% url "cheat:mySheets"  %}">
                    <button>View my CheatSheets</button>
                </a>
                <a href="#">
                    <button>Add CheatSheet</button>
                </a>
                
               

            </div>
        </div>
        {% endblock %}
        
    </div>


    
    
</body>
        
</html>